version: '3'
services:
  bestbite-web:
    build: ./services/web/
    container_name: bestbite-web
    restart: unless-stopped
    ports:
      - '3007:3006' # expose ports - HOST:CONTAINER
    volumes:
      - ./services/web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development